name: 'Urban_Mobility_Demo_Luminates_2025'
config-version: 2
version: '1.0.0'

profile: 'urban_mobility_demo'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Urban_Mobility_Demo_Luminates_2025:
    +materialized: view
    +schema: "{{ target.schema }}"
