urban_mobility_demo:
  target: prod
  outputs:
    prod:
      type: snowflake
      threads: 8
      account: {{ env_var('SNOWFLAKE_ACCOUNT') }} 
      user: {{ env_var('SNOWFLAKE_USERNAME') }}
      password: {{ env_var('SNOWFLAKE_PASSWORD') }}
      role: {{ env_var('SNOWFLAKE_ROLE') }}
      database: "DE_LUMINATE_PROD"
      warehouse: {{ env_var('SNOWFLAKE_WAREHOUSE') }}
      schema: "URBAN_MOBILITY"
      client_session_keep_alive: False